#!/usr/bin/env bash
echo "Suoritetaan barstart" > $HOME/dotfiles/log/barstart
killall -q polybar


while pgrep -x polybar >/dev/null; do sleep 2; done

# Launch top bar
if [[ -z ${TATU_SETUP_POLYBAR_BAR+x} ]] ; then
    echo "Muuttuja TATU_SETUP_POLYBAR_BAR on asettamatta" > $HOME/dotfiles/log/barstart
    . ~/dotfiles/profile
fi

polybar $TATU_SETUP_POLYBAR_BAR > $HOME/dotfiles/log/barstart2 &
