#!/bin/bash

function f() {
    dir=~/keepass/
    if ! command -v inotifywait >> /dev/null; then
        notify-send "inotifywait komento on asentamatta"
        return
    fi

    while inotifywait -r -e modify,create,delete $dir; do
        notify-send "KeePass päivitetty"
        rsync -avz $dir password_server:~/keepass/
    done
}
f &
