#!/bin/bash

function f() {
    dir=~/keepass/
    if ! command -v inotifywait >> /dev/null; then
        notify-send "inotifywait komento on asentamatta"
        return
    fi

    if [[ ! -d $dir ]]; then
        notify-send "Ei ole Keepass kansiota, tehdään ja ladataan"
        mkdir $dir
        rsync -avz password_server:~/keepass/ $dir
    fi


    while inotifywait -r -e modify,create,delete $dir; do
        notify-send "KeePass päivitetty"
        rsync -avz $dir password_server:~/keepass/
    done
}
f &
